apiVersion: v1
kind: Pod
metadata:
  name: silly2
  labels:
    type: stack
    vendor: barak
spec:
  containers:
  - name: silly
    image: barakb/silly-demo:168e4bf
  - name: another-silly
    image: barakb/silly-demo:168e4bf
    env:
      - name: SPRING.APPLICATION_NAME
        value: "silly2"
      - name: SERVER_PORT
        value: "8081"
      - name: MANAGEMENT_SERVER_PORT
        value: "9091"
