name: build

on:
  pull_request:
    branches:
      - master
      - 'release/v*'
  push:
    branches:
      - master
      - 'release/v*'
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
      - name: compute short sha and current time
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=current_time::$(date +%s)"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Docker Push
        run: |
          ./mvnw install spring-boot:build-image -TC2 -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/silly-demo
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/silly-demo:${{ steps.vars.outputs.sha_short }}